version: '3.9'
services:
  php-env: 
    build:
      context: .  
      dockerfile: Dockerfile.prod 
    volumes:
      - ./htdocs:/var/www/html/htdocs
    ports:
      - 80:80
    environment:
      - APP_ENV=production
      - DB_HOST=${RDS_HOSTNAME}
      - DB_DATABASE=${RDS_DB_NAME}
      - DB_USERNAME=${RDS_USERNAME}
      - DB_PASSWORD=${RDS_PASSWORD}
    depends_on:
      - mysql_db
